### ISSUE TITLE
Проверка заданий

### ISSUE THREAD

**Issue by sofiasoyka** [sofiasoyka/programming#1]
Добрый вечер! Прошу проверить два задания

**Comment by FlashAnton** [comment]
> Добрый вечер! Прошу проверить два задания

Замечания по 1-й и 2-й работам сформулированы в соответствующих отчётах.

В 1-й работе необходимо пересмотреть код ПО и внести необходимые правки в отчёт.
Во 2-й работе необходимо внести правки только в отчёт. Наиболее критичное замечание там к блок-схеме.

**Comment by sofiasoyka** [comment]
Вы написали про отсутствие красной строки. Хочу уточнить - в отчетах по информатике тоже не было красной строки, там это не критично или все таки она нужна и в отчетах по информатике?

**Comment by FlashAnton** [comment]
> Вы написали про отсутствие красной строки. Хочу уточнить - в отчетах по Информатике тоже не было красной строки, там это не критично или все таки она нужна и в отчетах по Информатике?

По-хорошему, красная строка должна быть везде, но в работах, где нет кода - это не так уж и заметно, а там, где появляется код - начинает бросаться в глаза и вызывать подобные вопросы.

Будут силы и желание - можете исправить это и в принятых в зачёт работах. Но не первоочерёдно.

**Comment by sofiasoyka** [comment]
Добрый вечер! Исправила ошибки, проверьте, пожалуйста, исправленный вариант

**Comment by FlashAnton** [comment]
> Добрый вечер! Исправила ошибки, проверьте, пожалуйста, исправленный вариант

Теперь всё в порядке.
Выставил маркеры о выполнении 1-й и 2-й работ.

**Обе задачи зачтены**
