### ISSUE TITLE
Проверка заданий 3, 4 и 5

### ISSUE THREAD

**Issue by sofiasoyka** [sofiasoyka/programming#3]
Добрый день!
Вроде теперь должны приходить уведомления на почту
Выложила 3 и 4 задания для проверки

**Comment by FlashAnton** [comment]
Здравствуйте.

Да, всё поступило, всё вижу. Сегодня-завтра постараюсь взяться за проверку.

**Comment by FlashAnton** [comment]
24.11.2022 - работа № 3 **зачтена**.

~~Замечания к работе №4:~~ (**работа зачтена 27.11.2022**)

- [x] на блок-схему необходимо добавить метки переходов согласно построенной логике

**Замечания к работе №5:**

- [x] в разделе блок-схемы изобразить схему переключения, а не каскад условных операторов
- [x] сказать "Нет" заголовкам, оторванным от основного содержимого (см. иллюстрацию ниже)

![image](https://user-images.githubusercontent.com/95698986/203834926-a7f09cf1-b15b-48d2-9b86-7982c1eee932.png)

**Comment by sofiasoyka** [comment]
Исправила ошибки в 4 и 5 заданиях. Проверьте, пожалуйста

**Comment by FlashAnton** [comment]
> Исправила ошибки в 4 и 5 заданиях. Проверьте, пожалуйста

С изображённой на блок-схеме реализацией переключения я всё ещё не согласен.

- [x] изобразить схему переключения согласно учебно-методическому руководству

**Comment by sofiasoyka** [comment]
> 

Я исправила схему. Посмотрите, так ли, пожалуйста

**Comment by FlashAnton** [comment]
> > 
> 
> Я исправила схему. Посмотрите, так ли, пожалуйста

Да, всё теперь корректно.

**5-я работа зачтена**. 07.12.2022
