### ISSUE TITLE
Проверка заданий 6 и 7

### ISSUE THREAD

**Issue by sofiasoyka** [sofiasoyka/programming#4]
Добрый вечер!
Сделала еще два задания, проверьте, пожалуйста

**Comment by FlashAnton** [comment]
**Замечания к задаче №6:**

- [ ] Тестовые примеры не соответствуют требованиям из постановки. Необходимо исправить.
~~- [x] В этой задаче достаточно простая схема алгоритма - она не требует такого большого количества ссылок, которые её перегружают. Необходимо исправить.~~
~~- [x] Не ясно, почему b0 - активный параметр, в то время, как это исходные данные. Необходимо исправить.~~
~~- [x] Работа, обозначенная на титульном листе, не соответствует содержимому отчёта. Необходимо исправить.~~
~~- [x] Выбранная для реализации циклическая конструкция не соответствует тематике данной работы. Необходимо исправить.~~
- [ ] Оба тестовых примера, которые сейчас представлены в работе - плохие. Как минимум, выбран грубый шаг. Необходимо исправить.
- [ ] Вычислительный процесс на блок-схеме разомкнут. Необходимо исправить.

**Замечания к задаче №7:**

- [ ] Блок-схема алгоритма содержит запрещённые связи. Необходимо исправить.
~~- [x] Блок-схема алгоритма не содержит центральную ось. Необходимо исправить.~~
~~- [x] Не ясны два момента ввода исходных данных на блок-схеме, в то время как в программе ничего подобного нет. Внесите в блок-схему алгоритма соответствие составленной программе.~~

**Comment by sofiasoyka** [comment]
Исправила ошибки в 6 и 7 заданиях. Проверьте, пожалуйста

**Comment by FlashAnton** [comment]
> Исправила ошибки в 6 и 7 заданиях. Проверьте, пожалуйста

Замечания устранены частично.
В документах указал проблемы явно.
После коммита - сможете посмотреть.

**Comment by sofiasoyka** [comment]
Поправила недочеты

**Comment by FlashAnton** [comment]
Все обсуждения работ после вчерашнего коммита - в очном формате с защитой.
